version: "3.8"
x-default-service-common: &default-service-common
  restart: unless-stopped
  networks:
    - shared

services:
  db:
    <<: *default-service-common
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      shared:
        aliases:
          - db
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'

    networks:
      shared:
        aliases:
          - phpmyadmin
volumes:
  mysql-data:
    name: mysql-data

networks:
  shared:
    name: main-network